// Oracle Help Command Extension
CommandProcessor.prototype.cmdOracleHelp = function() {
    this.terminal.writeln('');
    this.terminal.writeln('=== Oracle Database 19c Installation Guide for RHEL 9 ===');
    this.terminal.writeln('');
    this.terminal.writeln('█▀▀ PREREQUISITES');
    this.terminal.writeln('─────────────────');
    this.terminal.writeln('1. Hardware Requirements:');
    this.terminal.writeln('   • RAM: Minimum 2GB (Recommended 8GB+)');
    this.terminal.writeln('   • Swap: 1.5x RAM when RAM < 16GB');
    this.terminal.writeln('   • Disk Space: 7.5GB for software + database files');
    this.terminal.writeln('   • Check: free -h, df -h');
    this.terminal.writeln('');
    this.terminal.writeln('2. Software Requirements:');
    this.terminal.writeln('   • RHEL 9.0 or later');
    this.terminal.writeln('   • Required packages: oracle-database-preinstall-19c');
    this.terminal.writeln('   • Check: cat /etc/redhat-release');
    this.terminal.writeln('');
    this.terminal.writeln('█▀▀ PREINSTALL TASKS');
    this.terminal.writeln('────────────────────');
    this.terminal.writeln('1. Create Oracle Groups:');
    this.terminal.writeln('   groupadd -g 54321 oinstall');
    this.terminal.writeln('   groupadd -g 54322 dba');
    this.terminal.writeln('   groupadd -g 54323 oper');
    this.terminal.writeln('   groupadd -g 54324 backupdba');
    this.terminal.writeln('   groupadd -g 54325 dgdba');
    this.terminal.writeln('   groupadd -g 54326 kmdba');
    this.terminal.writeln('   groupadd -g 54327 racdba');
    this.terminal.writeln('');
    this.terminal.writeln('2. Create Oracle User:');
    this.terminal.writeln('   useradd -u 54321 -g oinstall -G dba,oper,backupdba,dgdba,kmdba,racdba oracle');
    this.terminal.writeln('   passwd oracle');
    this.terminal.writeln('');
    this.terminal.writeln('3. Configure Kernel Parameters:');
    this.terminal.writeln('   vim /etc/sysctl.conf');
    this.terminal.writeln('   # Add the following:');
    this.terminal.writeln('   fs.aio-max-nr = 1048576');
    this.terminal.writeln('   fs.file-max = 6815744');
    this.terminal.writeln('   kernel.shmall = 2097152');
    this.terminal.writeln('   kernel.shmmax = 4294967295');
    this.terminal.writeln('   kernel.shmmni = 4096');
    this.terminal.writeln('   kernel.sem = 250 32000 100 128');
    this.terminal.writeln('   net.ipv4.ip_local_port_range = 9000 65500');
    this.terminal.writeln('   net.core.rmem_default = 262144');
    this.terminal.writeln('   net.core.rmem_max = 4194304');
    this.terminal.writeln('   net.core.wmem_default = 262144');
    this.terminal.writeln('   net.core.wmem_max = 1048576');
    this.terminal.writeln('   # Apply: sysctl -p');
    this.terminal.writeln('');
    this.terminal.writeln('4. Configure Resource Limits:');
    this.terminal.writeln('   vim /etc/security/limits.conf');
    this.terminal.writeln('   # Add the following:');
    this.terminal.writeln('   oracle soft nproc 2047');
    this.terminal.writeln('   oracle hard nproc 16384');
    this.terminal.writeln('   oracle soft nofile 1024');
    this.terminal.writeln('   oracle hard nofile 65536');
    this.terminal.writeln('   oracle soft stack 10240');
    this.terminal.writeln('   oracle hard stack 32768');
    this.terminal.writeln('');
    this.terminal.writeln('5. Create Oracle Directories:');
    this.terminal.writeln('   mkdir -p /u01/app/oracle/product/19.0.0/dbhome_1');
    this.terminal.writeln('   mkdir -p /u01/app/oraInventory');
    this.terminal.writeln('   chown -R oracle:oinstall /u01');
    this.terminal.writeln('   chmod -R 775 /u01');
    this.terminal.writeln('');
    this.terminal.writeln('6. Configure Environment Variables:');
    this.terminal.writeln('   su - oracle');
    this.terminal.writeln('   vim ~/.bash_profile');
    this.terminal.writeln('   # Add:');
    this.terminal.writeln('   export ORACLE_BASE=/u01/app/oracle');
    this.terminal.writeln('   export ORACLE_HOME=$ORACLE_BASE/product/19.0.0/dbhome_1');
    this.terminal.writeln('   export ORACLE_SID=ORCL');
    this.terminal.writeln('   export PATH=$ORACLE_HOME/bin:$PATH');
    this.terminal.writeln('   export LD_LIBRARY_PATH=$ORACLE_HOME/lib:$LD_LIBRARY_PATH');
    this.terminal.writeln('');
    this.terminal.writeln('7. Disable Firewall & SELinux (for installation):');
    this.terminal.writeln('   systemctl stop firewalld');
    this.terminal.writeln('   systemctl disable firewalld');
    this.terminal.writeln('   setenforce 0');
    this.terminal.writeln('   vim /etc/selinux/config');
    this.terminal.writeln('   # Set SELINUX=permissive');
    this.terminal.writeln('');
    this.terminal.writeln('█▀▀ INSTALLATION');
    this.terminal.writeln('────────────────');
    this.terminal.writeln('1. Download Oracle 19c from Oracle website');
    this.terminal.writeln('2. Extract as oracle user:');
    this.terminal.writeln('   su - oracle');
    this.terminal.writeln('   cd $ORACLE_HOME');
    this.terminal.writeln('   unzip /path/to/LINUX.X64_193000_db_home.zip');
    this.terminal.writeln('');
    this.terminal.writeln('3. Run Installer:');
    this.terminal.writeln('   ./runInstaller');
    this.terminal.writeln('   # Follow GUI prompts');
    this.terminal.writeln('   # Select: Install database software only');
    this.terminal.writeln('   # Choose: Single instance database');
    this.terminal.writeln('   # Select: Enterprise Edition');
    this.terminal.writeln('   # Set ORACLE_BASE: /u01/app/oracle');
    this.terminal.writeln('   # Set Inventory: /u01/app/oraInventory');
    this.terminal.writeln('');
    this.terminal.writeln('4. Run Root Scripts (as root):');
    this.terminal.writeln('   /u01/app/oraInventory/orainstRoot.sh');
    this.terminal.writeln('   /u01/app/oracle/product/19.0.0/dbhome_1/root.sh');
    this.terminal.writeln('');
    this.terminal.writeln('█▀▀ POST-INSTALL TASKS');
    this.terminal.writeln('──────────────────────');
    this.terminal.writeln('1. Create Database using DBCA:');
    this.terminal.writeln('   su - oracle');
    this.terminal.writeln('   dbca');
    this.terminal.writeln('   # Follow wizard to create database');
    this.terminal.writeln('   # Typical settings:');
    this.terminal.writeln('   # - Global Database Name: ORCL');
    this.terminal.writeln('   # - SID: ORCL');
    this.terminal.writeln('   # - Create as Container Database');
    this.terminal.writeln('   # - Memory: Use Automatic Memory Management');
    this.terminal.writeln('');
    this.terminal.writeln('2. Configure Listener:');
    this.terminal.writeln('   netca');
    this.terminal.writeln('   # Create default LISTENER on port 1521');
    this.terminal.writeln('');
    this.terminal.writeln('3. Enable Oracle at Startup:');
    this.terminal.writeln('   vim /etc/oratab');
    this.terminal.writeln('   # Change N to Y for your database:');
    this.terminal.writeln('   # ORCL:/u01/app/oracle/product/19.0.0/dbhome_1:Y');
    this.terminal.writeln('');
    this.terminal.writeln('█▀▀ TESTING & VERIFICATION');
    this.terminal.writeln('──────────────────────────');
    this.terminal.writeln('1. Check Listener Status:');
    this.terminal.writeln('   lsnrctl status');
    this.terminal.writeln('');
    this.terminal.writeln('2. Connect to Database:');
    this.terminal.writeln('   sqlplus / as sysdba');
    this.terminal.writeln('   SQL> SELECT name, open_mode FROM v$database;');
    this.terminal.writeln('   SQL> SELECT instance_name, status FROM v$instance;');
    this.terminal.writeln('');
    this.terminal.writeln('3. Check Alert Log:');
    this.terminal.writeln('   cd $ORACLE_BASE/diag/rdbms/orcl/ORCL/trace');
    this.terminal.writeln('   tail -f alert_ORCL.log');
    this.terminal.writeln('');
    this.terminal.writeln('4. Test Remote Connection:');
    this.terminal.writeln('   sqlplus system@localhost:1521/ORCL');
    this.terminal.writeln('');
    this.terminal.writeln('█▀▀ COMMON ISSUES & SOLUTIONS');
    this.terminal.writeln('─────────────────────────────');
    this.terminal.writeln('• "cannot open shared object file"');
    this.terminal.writeln('  → Check LD_LIBRARY_PATH, run ldconfig');
    this.terminal.writeln('');
    this.terminal.writeln('• "ORA-12541: TNS:no listener"');
    this.terminal.writeln('  → Start listener: lsnrctl start');
    this.terminal.writeln('');
    this.terminal.writeln('• "ORA-01034: ORACLE not available"');
    this.terminal.writeln('  → Start database: startup (in sqlplus)');
    this.terminal.writeln('');
    this.terminal.writeln('• Installation fails on prerequisites');
    this.terminal.writeln('  → Install: yum install oracle-database-preinstall-19c');
    this.terminal.writeln('');
    this.terminal.writeln('█▀▀ PRACTICE COMMANDS IN THIS SIMULATOR');
    this.terminal.writeln('───────────────────────────────────────');
    this.terminal.writeln('# You can practice all preinstall tasks here:');
    this.terminal.writeln('groupadd oinstall');
    this.terminal.writeln('useradd -g oinstall -G dba oracle');
    this.terminal.writeln('mkdir -p /u01/app/oracle/product/19.0.0/dbhome_1');
    this.terminal.writeln('vim /etc/sysctl.conf');
    this.terminal.writeln('cat /etc/passwd | grep oracle');
    this.terminal.writeln('id oracle');
    this.terminal.writeln('');
    this.terminal.writeln('For more help, type: help');
    this.terminal.writeln('');
};